### ISSUE TITLE
Custom knight update is broken because of this mod, please update.

### ISSUE THREAD

**Issue by Samrox2004** [KayDeeTee/hk-moresaves#5]
A post from the hollow knight modding discord says this,

It's also been discovered that there's currently a bug involving the MoreSaves mod. If you are using that, then Custom Knight won't work properly until it is updated to fix it.

Please fix the mod so we can all use custom skins with this mod enabled.

**Comment by KayDeeTee** [comment]
Thanks for telling me that my mod that hasn't been updated in like 4years and is maintained by someone else in a different repository and isn't the one you have installed breaks another mod.
Please forward all your complaints to the actual repo here: https://github.com/TheMulhima/MoreSaves/tree/master/MoreSaves

**Comment by Samrox2004** [comment]
There is no need to as it has been updated and the issue has been fixed
